// Homepage with mission selection

import Link from "next/link"
import { missions } from "@/lib/data/missions"

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 via-purple-900 to-slate-900">
      {/* Hero Section */}
      <header className="container mx-auto px-4 py-16 text-center">
        <h1 className="text-5xl md:text-7xl font-bold text-white mb-6">YaisBio Classroom</h1>
        <p className="text-xl md:text-2xl text-purple-200 mb-8 max-w-3xl mx-auto">
          Transform NASA space biology research into interactive learning adventures
        </p>
        <div className="flex gap-4 justify-center flex-wrap">
          <Link
            href="/missions"
            className="bg-green-500 hover:bg-green-600 text-white px-8 py-4 rounded-lg text-lg font-semibold transition-colors"
          >
            Start Exploring
          </Link>
          <Link
            href="/dashboard"
            className="bg-purple-600 hover:bg-purple-700 text-white px-8 py-4 rounded-lg text-lg font-semibold transition-colors"
          >
            My Progress
          </Link>
          <Link
            href="/analytics"
            className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-4 rounded-lg text-lg font-semibold transition-colors"
          >
            Research Analytics
          </Link>
        </div>
      </header>

      {/* Features */}
      <section className="container mx-auto px-4 py-16">
        <div className="grid md:grid-cols-3 gap-8">
          <div className="bg-white/10 backdrop-blur-lg rounded-xl p-8 text-white">
            <div className="text-4xl mb-4">🚀</div>
            <h3 className="text-2xl font-bold mb-3">Immersive Narratives</h3>
            <p className="text-purple-200">Experience NASA research through engaging space mission stories</p>
          </div>
          <div className="bg-white/10 backdrop-blur-lg rounded-xl p-8 text-white">
            <div className="text-4xl mb-4">🌍</div>
            <h3 className="text-2xl font-bold mb-3">Bilingual Learning</h3>
            <p className="text-purple-200">Switch seamlessly between Spanish and English</p>
          </div>
          <div className="bg-white/10 backdrop-blur-lg rounded-xl p-8 text-white">
            <div className="text-4xl mb-4">🤖</div>
            <h3 className="text-2xl font-bold mb-3">AI-Powered</h3>
            <p className="text-purple-200">Personalized content generated by Google Gemini</p>
          </div>
        </div>
      </section>

      {/* Mission Preview */}
      <section className="container mx-auto px-4 py-16">
        <h2 className="text-4xl font-bold text-white text-center mb-12">Featured Missions</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {missions.slice(0, 6).map((mission) => (
            <Link
              key={mission.id}
              href={`/missions/${mission.id}`}
              className="bg-white/10 backdrop-blur-lg rounded-xl p-6 text-white hover:bg-white/20 transition-all transform hover:scale-105"
            >
              <div className="flex items-center gap-2 mb-3">
                <span
                  className={`px-3 py-1 rounded-full text-sm font-semibold ${
                    mission.level === "beginner"
                      ? "bg-green-500"
                      : mission.level === "intermediate"
                        ? "bg-yellow-500"
                        : "bg-red-500"
                  }`}
                >
                  {mission.level}
                </span>
                <span className="text-purple-200 text-sm">{mission.duration} min</span>
              </div>
              <h3 className="text-xl font-bold mb-2">{mission.titleEs}</h3>
              <p className="text-purple-200 text-sm">{mission.descriptionEs}</p>
            </Link>
          ))}
        </div>
        <div className="text-center mt-8">
          <Link href="/missions" className="text-green-400 hover:text-green-300 font-semibold text-lg">
            View All Missions →
          </Link>
        </div>
      </section>

      {/* Stats */}
      <section className="container mx-auto px-4 py-16">
        <div className="bg-white/10 backdrop-blur-lg rounded-xl p-12">
          <div className="grid md:grid-cols-4 gap-8 text-center text-white">
            <div>
              <div className="text-4xl font-bold text-green-400 mb-2">608</div>
              <div className="text-purple-200">NASA Papers</div>
            </div>
            <div>
              <div className="text-4xl font-bold text-green-400 mb-2">10</div>
              <div className="text-purple-200">Missions (MVP)</div>
            </div>
            <div>
              <div className="text-4xl font-bold text-green-400 mb-2">20</div>
              <div className="text-purple-200">Badges to Earn</div>
            </div>
            <div>
              <div className="text-4xl font-bold text-green-400 mb-2">2</div>
              <div className="text-purple-200">Languages</div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="container mx-auto px-4 py-8 text-center text-purple-200">
        <p className="mb-4">Part of the YAIS Ecosystem</p>
        <div className="flex gap-6 justify-center flex-wrap">
          <Link href="/missions" className="hover:text-white">
            Missions
          </Link>
          <Link href="/dashboard" className="hover:text-white">
            Dashboard
          </Link>
          <Link href="/glossary" className="hover:text-white">
            Glossary
          </Link>
          <Link href="/propose" className="hover:text-white">
            Propose Experiment
          </Link>
          <a href="https://yais.org" target="_blank" rel="noopener noreferrer" className="hover:text-white">
            YAIS Lab
          </a>
        </div>
      </footer>
    </div>
  )
}
